
name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest  # GitHub Actions Runner Images
        steps:
            - name: Checkout code on runner machine
            uses: actions/checkout@v4  # It will chekout you repository under workplace

            
            - name: Run some commands
            run: |   # | For Run multiple command with diffrent lines
             ls -al
             whoami
             pwd
